task: detection

num_classes: 1
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /content/drive/MyDrive/TA_New/dataset/dry/dry_dataset.coco/train/
    ann_file: /content/drive/MyDrive/TA_New/dataset/dry/dry_dataset.coco/train/_annotations.coco.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4
  num_workers: 2
  drop_last: True

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /content/drive/MyDrive/TA_New/dataset/dry/dry_dataset.coco/valid
    ann_file: /content/drive/MyDrive/TA_New/dataset/dry/dry_dataset.coco/valid/_annotations.coco.json
    transforms:
      type: Compose
      ops: ~

  shuffle: False
  batch_size: 4
  num_workers: 2
  drop_last: False
